# Generated by Django 5.1.5 on 2025-01-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spam', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spamreport',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
